print ("Hey There! Pls enter Values for a , b , c , d and e.")
a= int(input("Enter Value for a : "))
b= int(input("Enter Value for b : "))
c= int(input("Enter Value for c : "))
d= int(input("Enter Value for d : "))
e= int(input("Enter Value for e : "))
z = (a,b,c,d,e)
x= max(z)
y=min(z)
p=max(z)-min(z)
s= sum(z) / len(z)
h= sum(z) / len(z)
print("The Maximum no. of the sets is : " , x )     
print("The Minimum no. of the sets is : " , y )
print ("The Average of the sets is : " , h )
print("The range of the sets is : " , p )
print ("The Mean of the sets is : " , s )

